FROM node:alpine

WORKDIR /app

COPY package.json yarn.lock next.config.js tsconfig.json .env environment.d.ts ./
COPY tailwind.config.js postcss.config.js ./
COPY prisma ./prisma
COPY src ./src

RUN npx prisma generate
RUN npm install
RUN npm run build

ENV NEXT_TELEMETRY_DISABLED=1

EXPOSE 3000

CMD [ "yarn", "dev" ]