FROM node:alpine

WORKDIR /app

# COPY package.json yarn.lock next.config.js tsconfig.json .env environment.d.ts ./
# COPY tailwind.config.js postcss.config.js ./
# COPY prisma ./prisma
# COPY src ./src
COPY . .
# RUN rm -r node_modules .next

RUN npx prisma generate
RUN npm install
RUN npm run build

ENV NEXT_TELEMETRY_DISABLED=1
# ENV NODE_ENV development
ENV NODE_ENV production

EXPOSE 3000

# CMD [ "yarn", "dev" ]
CMD [ "yarn", "start" ]