version: '3'

services:
  app:
    container_name: app
    image: docker-nextjs-dev
    build:
      context: .
      dockerfile: Dockerfile.${ENV}
    ports:
      - 3000:3000
    env_file: .env
    volumes:
      - ./src:/app/src
      - ./public:/app/public